// Generated by workflow/generate-scene-session-methods.js. Review additions as public RPC surface.
export const sceneSessionMethods: Record<string, readonly string[]> = {
    "Editor": [
        "applyRecordedChanges",
        "close",
        "create",
        "hasOpen",
        "open",
        "queryCurrent",
        "querySceneSerializedData",
        "reload",
        "save"
    ],
    "Node": [
        "copy",
        "createByAsset",
        "createBySerializedData",
        "createByType",
        "cut",
        "delete",
        "duplicate",
        "getPathByUuid",
        "paste",
        "query",
        "queryNodeTree",
        "reorder",
        "resetProperty",
        "serialize",
        "setParent",
        "setProperty"
    ],
    "Component": [
        "add",
        "eraseLOD",
        "getPathByUuid",
        "insertLOD",
        "query",
        "queryAll",
        "queryLODGroupRelativeHeight",
        "recalculateLODGroupBounds",
        "regeneratePolygon2DPoints",
        "remove",
        "setProperty"
    ],
    "Prefab": [
        "applyPrefabChanges",
        "createPrefabFromNode",
        "getPrefabInfo",
        "isPrefabInstance",
        "revertToPrefab",
        "unlinkPrefab",
        "unpackPrefabInstance"
    ],
    "Selection": [
        "clear",
        "isSelect",
        "query",
        "select",
        "unselect"
    ],
    "Undo": [
        "canUndo",
        "isDirty",
        "undo"
    ],
    "Redo": [
        "canRedo",
        "redo"
    ],
    "ReferenceImage": [
        "addAndSelect",
        "clearBinding",
        "commitParameters",
        "getState",
        "refresh",
        "remove",
        "select",
        "setVisible"
    ],
    "Terrain": [
        "addAssetToComp",
        "addLayer",
        "close",
        "read",
        "readBlock",
        "removeLayer",
        "saveAsset",
        "saveAssetDialog",
        "saveManage",
        "select",
        "setCurrentLayer",
        "setMode",
        "setPaintBrushAsset",
        "setPaintSession",
        "setSculptBrushAsset",
        "setSculptSession",
        "unselect",
        "updateLayer"
    ]
};
